In [21]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
%matplotlib inline 
from sklearn.linear_model import LogisticRegression 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import log_loss

In [22]:
import warnings
warnings.filterwarnings('ignore')

In [23]:
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/ChurnData.csv"
churn_df = pd.read_csv(url)

In [24]:
churn_df.describe()

           tenure         age     address  ...       lninc     custcat       churn
count  200.000000  200.000000  200.000000  ...  200.000000  200.000000  200.000000
mean    35.505000   41.165000   11.650000  ...    3.951015    2.475000    0.290000
std     21.640971   13.076803   10.158419  ...    0.752553    1.079445    0.454901
min      1.000000   19.000000    0.000000  ...    2.197000    1.000000    0.000000
25%     16.750000   31.000000    3.000000  ...    3.434000    2.000000    0.000000
50%     33.500000   40.000000    9.000000  ...    3.871000    2.000000    0.000000
75%     55.250000   51.000000   18.000000  ...    4.382000    3.000000    1.000000
max     72.000000   76.000000   48.000000  ...    7.419000    4.000000    1.000000

[8 rows x 28 columns]

In [25]:
churn_df = churn_df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip', 'churn']]
churn_df

     tenure   age  address  income   ed  employ  equip  churn
0      11.0  33.0      7.0   136.0  5.0     5.0    0.0    1.0
1      33.0  33.0     12.0    33.0  2.0     0.0    0.0    1.0
2      23.0  30.0      9.0    30.0  1.0     2.0    0.0    0.0
3      38.0  35.0      5.0    76.0  2.0    10.0    1.0    0.0
4       7.0  35.0     14.0    80.0  2.0    15.0    0.0    0.0
..      ...   ...      ...     ...  ...     ...    ...    ...
195    55.0  44.0     24.0    83.0  1.0    23.0    0.0    0.0
196    34.0  23.0      3.0    24.0  1.0     7.0    0.0    0.0
197     6.0  32.0     10.0    47.0  1.0    10.0    0.0    0.0
198    24.0  30.0      0.0    25.0  4.0     5.0    0.0    1.0
199    61.0  50.0     16.0   190.0  2.0    22.0    1.0    0.0

[200 rows x 8 columns]

In [26]:
churn_df['churn'] = churn_df['churn'].astype(int)
churn_df

     tenure   age  address  income   ed  employ  equip  churn
0      11.0  33.0      7.0   136.0  5.0     5.0    0.0      1
1      33.0  33.0     12.0    33.0  2.0     0.0    0.0      1
2      23.0  30.0      9.0    30.0  1.0     2.0    0.0      0
3      38.0  35.0      5.0    76.0  2.0    10.0    1.0      0
4       7.0  35.0     14.0    80.0  2.0    15.0    0.0      0
..      ...   ...      ...     ...  ...     ...    ...    ...
195    55.0  44.0     24.0    83.0  1.0    23.0    0.0      0
196    34.0  23.0      3.0    24.0  1.0     7.0    0.0      0
197     6.0  32.0     10.0    47.0  1.0    10.0    0.0      0
198    24.0  30.0      0.0    25.0  4.0     5.0    0.0      1
199    61.0  50.0     16.0   190.0  2.0    22.0    1.0      0

[200 rows x 8 columns]

In [27]:
X = np.asarray(churn_df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip']])
X[0:5]

array([[ 11.,  33.,   7., 136.,   5.,   5.,   0.],
       [ 33.,  33.,  12.,  33.,   2.,   0.,   0.],
       [ 23.,  30.,   9.,  30.,   1.,   2.,   0.],
       [ 38.,  35.,   5.,  76.,   2.,  10.,   1.],
       [  7.,  35.,  14.,  80.,   2.,  15.,   0.]])

In [28]:
y = np.asarray(churn_df['churn'])
y[0:5]

array([1, 1, 0, 0, 0])

In [29]:
X_norm = StandardScaler().fit(X).transform(X)
X_norm[0:5]

array([[-1.13518441, -0.62595491, -0.4588971 ,  0.4751423 ,  1.6961288 ,
        -0.58477841, -0.85972695],
       [-0.11604313, -0.62595491,  0.03454064, -0.32886061, -0.6433592 ,
        -1.14437497, -0.85972695],
       [-0.57928917, -0.85594447, -0.261522  , -0.35227817, -1.42318853,
        -0.92053635, -0.85972695],
       [ 0.11557989, -0.47262854, -0.65627219,  0.00679109, -0.6433592 ,
        -0.02518185,  1.16316   ],
       [-1.32048283, -0.47262854,  0.23191574,  0.03801451, -0.6433592 ,
         0.53441472, -0.85972695]])

In [30]:
X_train,X_test,y_train,y_test = train_test_split(X_norm,y,test_size = 0.2,random_state = 42)

In [33]:
LR = LogisticRegression()
LR.fit(X_train,y_train)

LogisticRegression()

In [34]:
yhat = LR.predict(X_test)
yhat

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0])