In [1]:
import numpy as np
import pandas as pd

In [2]:
labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d= {'a':10,'b':20,'c':30}

In [3]:
pd.Series(data = my_data)

0    10
1    20
2    30
dtype: int64

In [4]:
pd.Series(data = my_data,index = labels)

a    10
b    20
c    30
dtype: int64

In [5]:
pd.Series(my_data,labels)

a    10
b    20
c    30
dtype: int64

In [6]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int64

In [7]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [8]:
d

{'a': 10, 'b': 20, 'c': 30}

In [9]:
ser1 = pd.Series([1,2,3,4],['usa','Germany','Japan','India'])
ser1

usa        1
Germany    2
Japan      3
India      4
dtype: int64

In [10]:
from numpy.random import randn

In [11]:
np.random.seed(101)

In [12]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [13]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [14]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [15]:
type(df['W'])

pandas.Series

In [16]:
type(df)

pandas.DataFrame

In [17]:
df[['W','X']]

          W         X
A  2.706850  0.628133
B  0.651118 -0.319318
C -2.018168  0.740122
D  0.188695 -0.758872
E  0.190794  1.978757

In [18]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [19]:
booldf = df >0

In [20]:
df[booldf]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [21]:
df['W'] >0

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [22]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [23]:
df[df['W']>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [24]:
df[df['Z']<0]

          W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

In [25]:
df[df['W']>0]['X']

A    0.628133
B   -0.319318
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [26]:
df[df['W']>0][['X','Y']]

          X         Y
A  0.628133  0.907969
B -0.319318 -0.848077
D -0.758872 -0.933237
E  1.978757  2.605967

In [27]:
df[(df['W']>0) & (df['Y']>1)]

          W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [28]:
df.reset_index(inplace = True)
df

  index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [29]:
newind = 'CA NY WY OR CO'.split()
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [30]:
df['States'] = newind

In [31]:
df

  index         W         X         Y         Z States
0     A  2.706850  0.628133  0.907969  0.503826     CA
1     B  0.651118 -0.319318 -0.848077  0.605965     NY
2     C -2.018168  0.740122  0.528813 -0.589001     WY
3     D  0.188695 -0.758872 -0.933237  0.955057     OR
4     E  0.190794  1.978757  2.605967  0.683509     CO

In [32]:
df.set_index('States')

       index         W         X         Y         Z
States
CA         A  2.706850  0.628133  0.907969  0.503826
NY         B  0.651118 -0.319318 -0.848077  0.605965
WY         C -2.018168  0.740122  0.528813 -0.589001
OR         D  0.188695 -0.758872 -0.933237  0.955057
CO         E  0.190794  1.978757  2.605967  0.683509

In [33]:
#index level
outside = ['G1','G2','G3','G4','G5']
inside = [1,2,3,4,5]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [34]:
outside

['G1', 'G2', 'G3', 'G4', 'G5']

In [35]:
hier_index

MultiIndex([('G1', 1),
            ('G2', 2),
            ('G3', 3),
            ('G4', 4),
            ('G5', 5)],
           )

In [36]:
list(zip(outside,inside))

[('G1', 1), ('G2', 2), ('G3', 3), ('G4', 4), ('G5', 5)]

In [37]:
df = pd.DataFrame(randn(5,2),hier_index,['A','B'])
df

             A         B
G1 1  0.302665  1.693723
G2 2 -1.706086 -1.159119
G3 3 -0.134841  0.390528
G4 4  0.166905  0.184502
G5 5  0.807706  0.072960

In [38]:
df.loc['G1']

          A         B
1  0.302665  1.693723

In [39]:
df.index.names = ['Groups','Num']
df

                   A         B
Groups Num
G1     1    0.302665  1.693723
G2     2   -1.706086 -1.159119
G3     3   -0.134841  0.390528
G4     4    0.166905  0.184502
G5     5    0.807706  0.072960

In [40]:
d = {'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]}

In [41]:
df = pd.DataFrame(d)
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [42]:
df.dropna(axis = 1)

   C
0  1
1  2
2  3

In [43]:
df.dropna()

     A    B  C
0  1.0  5.0  1

In [44]:
df.fillna(value = 'FILL VAUEW')

            A           B  C
0         1.0         5.0  1
1         2.0  FILL VAUEW  2
2  FILL VAUEW  FILL VAUEW  3

In [45]:
df['A'].fillna(value = df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [46]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
        'Person':['Sam','Charlie','Amy','Vanessa','Crl','Sarah'],
        'Sales':[200,120,340,124,243,350]}

In [47]:
df = pd.DataFrame(data)

In [48]:
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB      Crl    243
5      FB    Sarah    350

In [49]:
byCom = df.groupby('Company')

In [50]:
byCom

In [ ]:
byCom.sum().loc['FB']

Person    CrlSarah
Sales          593
Name: FB, dtype: object

In [52]:
df = pd.DataFrame({
    'col1':[1,2,3,4],
    'col2':[444,555,666,444],
    'col3':['abc','def','ghi','xyz']
})

In [53]:
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [57]:
df['col2'].unique()

array([444, 555, 666])

In [58]:
df['col2'].nunique()

3

In [59]:
df['col2'].value_counts()

col2
444    2
555    1
666    1
Name: count, dtype: int64