In [2]:
import numpy as np
import pandas as pd

In [3]:
labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d= {'a':10,'b':20,'c':30}

In [4]:
pd.Series(data = my_data)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series(data = my_data,index = labels)

a    10
b    20
c    30
dtype: int64

In [6]:
pd.Series(my_data,labels)

a    10
b    20
c    30
dtype: int64

In [8]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int64

In [9]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [10]:
d

{'a': 10, 'b': 20, 'c': 30}

In [12]:
ser1 = pd.Series([1,2,3,4],['usa','Germany','Japan','India'])
ser1

usa        1
Germany    2
Japan      3
India      4
dtype: int64

In [13]:
from numpy.random import randn

In [14]:
np.random.seed(101)

In [15]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [16]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [17]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [18]:
type(df['W'])

pandas.Series

In [19]:
type(df)

pandas.DataFrame

In [20]:
df[['W','X']]

          W         X
A  2.706850  0.628133
B  0.651118 -0.319318
C -2.018168  0.740122
D  0.188695 -0.758872
E  0.190794  1.978757

In [22]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [23]:
booldf = df >0

In [25]:
df[booldf]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [26]:
df['W'] >0

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [27]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [28]:
df[df['W']>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [30]:
df[df['Z']<0]

          W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

In [31]:
df[df['W']>0]['X']

A    0.628133
B   -0.319318
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [32]:
df[df['W']>0][['X','Y']]

          X         Y
A  0.628133  0.907969
B -0.319318 -0.848077
D -0.758872 -0.933237
E  1.978757  2.605967

In [33]:
df[(df['W']>0) & (df['Y']>1)]

          W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [36]:
df.reset_index(inplace = True)
df

   level_0 index         W         X         Y         Z
0        0     A  2.706850  0.628133  0.907969  0.503826
1        1     B  0.651118 -0.319318 -0.848077  0.605965
2        2     C -2.018168  0.740122  0.528813 -0.589001
3        3     D  0.188695 -0.758872 -0.933237  0.955057
4        4     E  0.190794  1.978757  2.605967  0.683509

In [37]:
newind = 'CA NY WY OR CO'.split()
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [38]:
df['States'] = newind

In [39]:
df

   level_0 index         W         X         Y         Z States
0        0     A  2.706850  0.628133  0.907969  0.503826     CA
1        1     B  0.651118 -0.319318 -0.848077  0.605965     NY
2        2     C -2.018168  0.740122  0.528813 -0.589001     WY
3        3     D  0.188695 -0.758872 -0.933237  0.955057     OR
4        4     E  0.190794  1.978757  2.605967  0.683509     CO